/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/toy.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.windowcolor}
        geometry={nodes.window.geometry}
        position={[-0.05, 3.87, 0.47]}
        scale={[2.01, 1.21, 2.59]}
      />
      <mesh
        material={materials.lightgrey}
        geometry={nodes.sireneeiland.geometry}
        position={[-0.85, 5.16, 0.12]}
        scale={[0.78, -0.51, 0.73]}
      />
      <mesh
        material={materials.lightred}
        geometry={nodes.sirene.geometry}
        position={[-0.86, 5.24, 0.11]}
        scale={[0.73, -0.86, 0.65]}
      />
      <group position={[-0.01, 1.79, 0.05]} scale={[7.62, 0.83, 2.91]}>
        <mesh material={materials.bodycolor} geometry={nodes.carbody_1.geometry} />
        <mesh material={materials.lightstripered} geometry={nodes.carbody_2.geometry} />
      </group>
      <mesh
        material={materials.white}
        geometry={nodes.plakkaten.geometry}
        position={[-0.01, 1.83, 2.99]}
        rotation={[-3.13, 0, 0]}
        scale={[3.65, 0.72, 0.03]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab.geometry}
        position={[-5.4, 1.59, 3]}
        rotation={[-1.61, -0.25, 3.13]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab001.geometry}
        position={[-5.7, 1.59, -2.89]}
        rotation={[-1.52, 0.25, -0.05]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab002.geometry}
        position={[2.51, 1.6, -3.07]}
        rotation={[-1.52, 0.25, -0.05]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab003.geometry}
        position={[2.72, 1.66, 3.17]}
        rotation={[-1.61, -0.25, 3.13]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab004.geometry}
        position={[-5.62, 0.8, 3.26]}
        rotation={[1.3, 0.22, 0.05]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab005.geometry}
        position={[-5.47, 0.8, -3.14]}
        rotation={[1.85, -0.22, -3.06]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab006.geometry}
        position={[2.74, 0.81, -3.33]}
        rotation={[1.85, -0.22, -3.06]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={materials.candylabcolor}
        geometry={nodes.candylab007.geometry}
        position={[2.5, 0.87, 3.43]}
        rotation={[1.3, 0.22, 0.05]}
        scale={[0.48, 0.7, 0.48]}
      />
      <mesh
        material={nodes.wheelplate.material}
        geometry={nodes.wheelplate.geometry}
        position={[-5.54, 1.19, 3]}
        rotation={[-1.58, 0.15, -0.03]}
        scale={[0.39, 0.02, 0.39]}
      />
      <mesh
        material={nodes.wheelplate001.material}
        geometry={nodes.wheelplate001.geometry}
        position={[2.64, 1.22, 3.15]}
        rotation={[-1.58, 0.15, -0.03]}
        scale={[0.39, 0.02, 0.39]}
      />
      <mesh
        material={materials.wheelplatecolor}
        geometry={nodes.littlewheelplate1.geometry}
        position={[-5.52, 1.19, 3.04]}
        rotation={[-1.58, 0.15, -0.03]}
        scale={[0.13, 0.01, 0.13]}
      />
      <mesh
        material={materials.wheelplatecolor}
        geometry={nodes.littlewheelplate2.geometry}
        position={[2.64, 1.25, 3.23]}
        rotation={[-1.58, 0.15, -0.03]}
        scale={[0.13, 0.01, 0.13]}
      />
      <mesh
        material={materials.yellow}
        geometry={nodes.shield.geometry}
        position={[0.22, 2.72, 2.91]}
        scale={[0.5, 0.5, 0.05]}
      />
      <mesh
        material={materials.darkgrey}
        geometry={nodes.wheels.geometry}
        position={[2.67, 1.2, 2.97]}
        rotation={[1.55, 0.43, -3.14]}
        scale={[0.79, 0.18, 0.79]}>
        <mesh material={materials.darkgrey} geometry={nodes.wheel.geometry} position={[9.39, 0.9, -4.26]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/toy.glb')
